/**
 * compress-models.js
 *
 * Скрипт для автоматической компрессии GLB/GLTF 3D-моделей
 *
 * ОПИСАНИЕ:
 * Этот скрипт автоматически находит и сжимает все несжатые .glb файлы в директории Data.
 * Он применяет различные методы оптимизации для уменьшения размера файлов без значительной
 * потери качества визуализации.
 *
 * ОСНОВНЫЕ ФУНКЦИИ:
 * - Автоматический поиск несжатых GLB файлов (без суффикса _compressed)
 * - Применение настраиваемых методов компрессии через конфигурационный файл
 * - Извлечение и сохранение якорей (анкоров) из 3D-моделей
 * - Генерация файла Anchors.js с координатами всех найденных якорей
 *
 * МЕТОДЫ КОМПРЕССИИ:
 * - Draco: геометрическая компрессия с квантизацией
 * - Simplify: упрощение полигональной сетки
 * - Texture Compress: сжатие текстур
 * - Instance: инстансинг повторяющейся геометрии
 * - Dedup: удаление дублирующихся данных
 * - Weld: объединение близких вершин
 * - Resample: ресемплинг анимаций
 * - Prune: удаление неиспользуемых ресурсов
 *
 * ИСПОЛЬЗОВАНИЕ:
 * npm run compress-models
 *
 * КОНФИГУРАЦИЯ:
 * Настройки компрессии находятся в файле model-compression-config.json
 * Можно задать как глобальные настройки (default), так и индивидуальные
 * для конкретных моделей (custom).
 *
 * ВЫХОДНЫЕ ФАЙЛЫ:
 * - {имя_модели}_compressed.glb - сжатые версии моделей
 * - App/AutoGeneratedData/Anchors.js - экспортированные координаты якорей
 */

const fs = require("fs");
const path = require("path");
const { NodeIO } = require("@gltf-transform/core");
const { ALL_EXTENSIONS } = require("@gltf-transform/extensions");
const draco3d = require("draco3d");
const meshoptimizer = require("meshoptimizer");
const sharp = require("sharp");
const {
  prune,
  dedup,
  resample,
  weld,
  instance,
  draco,
  reorder,
  flatten,
  simplify,
  textureCompress,
} = require("@gltf-transform/functions");
const { Vector3, Quaternion, Matrix4 } = require("three");

/**
 * Класс для компрессии GLB/GLTF файлов
 *
 * Обрабатывает 3D-модели, применяя различные методы оптимизации
 * и извлекая информацию о якорях для использования в приложении
 */
class GLBCompressor {
  /**
   * Конструктор класса GLBCompressor
   *
   * Инициализирует пути к файлам и загружает конфигурацию компрессии.
   *
   * @property {string} projectRoot - Корневая директория проекта
   * @property {string} configPath - Путь к файлу конфигурации
   * @property {string} dataDirectory - Директория с 3D-моделями
   * @property {string} anchorsFilePath - Путь для сохранения файла с якорями
   * @property {Object} modelAnchors - Объект для хранения извлеченных якорей
   * @property {Object} compressionConfig - Загруженная конфигурация компрессии
   */
  constructor() {
    this.projectRoot = path.resolve(__dirname, "..");
    this.configPath = path.join(__dirname, "model-compression-config.json");
    this.dataDirectory = path.join(this.projectRoot, "Data");
    this.anchorsFilePath = path.join(
      this.projectRoot,
      "App/AutoGeneratedData/Anchors.js",
    );
    this.modelAnchors = {};
    this.compressionConfig = this.loadCompressionConfig();
  }

  /**
   * Загружает конфигурацию компрессии из JSON файла
   *
   * @returns {Object} Объект с настройками компрессии
   * @throws {Error} Если файл конфигурации не найден
   */
  loadCompressionConfig() {
    if (!fs.existsSync(this.configPath)) {
      throw new Error("Missing compression-config.json next to script.");
    }
    return JSON.parse(fs.readFileSync(this.configPath, "utf8"));
  }

  /**
   * Находит все несжатые GLB файлы в директории Data
   *
   * Рекурсивно сканирует директорию и возвращает пути к файлам,
   * которые заканчиваются на .glb, но не содержат суффикс _compressed
   *
   * @returns {string[]} Массив путей к несжатым GLB файлам
   */
  findUncompressedGLBFiles() {
    const allFiles = this.walkDirectory(this.dataDirectory);
    return allFiles.filter((filePath) => {
      const fileName = path.basename(filePath);
      return fileName.endsWith(".glb") && !fileName.endsWith("_compressed.glb");
    });
  }

  /**
   * Рекурсивно обходит директорию и собирает все файлы
   *
   * @param {string} directory - Путь к директории для сканирования
   * @returns {string[]} Массив путей ко всем найденным файлам
   */
  walkDirectory(directory) {
    const entries = fs.readdirSync(directory, { withFileTypes: true });
    const files = [];

    for (const entry of entries) {
      const fullPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        files.push(...this.walkDirectory(fullPath));
      } else {
        files.push(fullPath);
      }
    }

    return files;
  }

  /**
   * Создает и настраивает экземпляр NodeIO для работы с GLTF/GLB файлами
   *
   * Инициализирует необходимые модули компрессии:
   * - Draco encoder для геометрической компрессии
   * - Meshoptimizer для оптимизации мешей
   *
   * @returns {Promise<NodeIO>} Настроенный экземпляр NodeIO
   */
  async createGLTFIO() {
    const dracoEncoder = await draco3d.createEncoderModule();
    await Promise.all([
      meshoptimizer.MeshoptEncoder.ready,
      meshoptimizer.MeshoptSimplifier.ready,
    ]);

    return new NodeIO()
      .registerExtensions(ALL_EXTENSIONS)
      .registerDependencies({
        "draco3d.encoder": dracoEncoder,
      });
  }

  /**
   * Извлекает якоря (анкоры) из 3D-модели
   *
   * Находит все ноды, имена которых начинаются с "ANC_" и извлекает
   * их трансформации (позиция, поворот, масштаб).
   *
   * Якоря используются для привязки интерактивных элементов или
   * других объектов к определенным точкам на 3D-модели.
   *
   * @param {Document} document - GLTF документ
   * @param {string} modelName - Имя модели (без расширения)
   */
  extractAnchors(document, modelName) {
    const anchors = document
      .getRoot()
      .listNodes()
      .filter((node) => node.getName().startsWith("ANC_"))
      .map((node) => {
        const transformMatrix = new Matrix4();
        transformMatrix.fromArray(node.getMatrix());

        const position = new Vector3();
        const quaternion = new Quaternion();
        const scale = new Vector3();
        transformMatrix.decompose(position, quaternion, scale);

        return {
          name: node.getName(),
          position: position.toArray(),
          quaternion: quaternion.toArray(),
          scale: scale.toArray(),
        };
      });

    if (anchors.length > 0) {
      this.modelAnchors[modelName] = anchors;
      console.log(`📦 Found ${anchors.length} anchors in ${modelName}.glb`);
    }
  }

  /**
   * Получает конфигурацию компрессии для конкретной модели
   *
   * Объединяет дефолтные настройки с кастомными настройками
   * для конкретной модели (если они заданы).
   *
   * @param {string} modelName - Имя модели
   * @returns {Object} Объединенная конфигурация компрессии
   */
  getModelConfig(modelName) {
    const defaultConfig = this.compressionConfig.default;
    const customConfig = this.compressionConfig.custom?.[modelName] || {};

    return {
      ...defaultConfig,
      ...customConfig,
    };
  }

  /**
   * Применяет трансформации компрессии к GLTF документу
   *
   * Последовательно применяет различные методы оптимизации согласно конфигурации:
   *
   * - flatten: Удаляет иерархию нод, оставляя только необходимые
   * - resample: Оптимизирует анимации путем уменьшения количества ключевых кадров
   * - dedup: Удаляет дублирующиеся вершины, материалы и текстуры
   * - weld: Объединяет близко расположенные вершины
   * - simplify: Упрощает геометрию, уменьшая количество полигонов
   * - reorder: Переупорядочивает данные для лучшего сжатия
   * - instance: Создает инстансы для повторяющейся геометрии
   * - draco: Применяет Draco компрессию к геометрии
   * - textureCompress: Сжимает и изменяет размер текстур
   * - prune: Удаляет неиспользуемые ресурсы
   *
   * @param {Document} document - GLTF документ для обработки
   * @param {string} modelName - Имя модели для получения конфигурации
   */
  async applyCompressionTransforms(document, modelName) {
    const config = this.getModelConfig(modelName);

    if (config.flatten) {
      await document.transform(flatten());
    }
    if (config.resample) {
      await document.transform(
        resample({ tolerance: config.resample.tolerance }),
      );
    }
    if (config.dedup) {
      await document.transform(dedup());
    }
    if (config.weld) {
      await document.transform(weld({ cleanup: false }));
    }
    if (config.simplify) {
      await document.transform(
        simplify({
          simplifier: meshoptimizer.MeshoptSimplifier,
          ratio: config.simplify.ratio,
          error: config.simplify.error,
        }),
      );
    }
    if (config.reorder) {
      await document.transform(
        reorder({ encoder: meshoptimizer.MeshoptEncoder }),
      );
    }
    if (config.instance) {
      await document.transform(instance({ min: config.instance.min }));
    }
    if (config.draco) {
      await document.transform(draco(config.draco));
    }
    if (config.textureCompress) {
      await document.transform(
        textureCompress({
          encoder: sharp,
          targetFormat: config.textureCompress.format,
          resize: Array.isArray(config.textureCompress.size)
            ? config.textureCompress.size
            : [config.textureCompress.size, config.textureCompress.size],
          quality: config.textureCompress.quality,
        }),
      );
    }
    if (config.prune) {
      await document.transform(prune());
    }
  }

  /**
   * Обрабатывает отдельный GLB файл
   *
   * Выполняет полный цикл обработки:
   * 1. Загружает GLB файл
   * 2. Извлекает якоря
   * 3. Применяет компрессию
   * 4. Сохраняет результат с суффиксом _compressed
   *
   * @param {string} filePath - Путь к исходному GLB файлу
   */
  async processGLBFile(filePath) {
    const inputFile = filePath;
    const directory = path.dirname(inputFile);
    const baseName = path.basename(filePath, ".glb");
    const outputFile = path.join(directory, `${baseName}_compressed.glb`);

    console.log(
      `➡️  Compressing: ${path.relative(this.dataDirectory, filePath)}`,
    );

    const io = await this.createGLTFIO();
    const document = await io.read(inputFile);

    this.extractAnchors(document, baseName);
    await this.applyCompressionTransforms(document, baseName);
    await io.write(outputFile, document);

    console.log(`✅ Written: ${path.relative(this.dataDirectory, outputFile)}`);
  }

  /**
   * Записывает извлеченные якоря в JavaScript файл
   *
   * Создает файл App/AutoGeneratedData/Anchors.js с экспортированным
   * объектом ANCHORS, содержащим все найденные якоря из обработанных моделей.
   *
   * Формат выходного файла:
   * export const ANCHORS = {
   *   "modelName": [
   *     {
   *       name: "ANC_point1",
   *       position: [x, y, z],
   *       quaternion: [x, y, z, w],
   *       scale: [x, y, z]
   *     }
   *   ]
   * };
   */
  writeAnchorsFile() {
    if (Object.keys(this.modelAnchors).length === 0) {
      return;
    }
    const outputContent =
      "// Auto-generated by compress-models.js\n\n" +
      "export const ANCHORS = " +
      JSON.stringify(this.modelAnchors, null, 2) +
      ";\n";

    fs.mkdirSync(path.dirname(this.anchorsFilePath), { recursive: true });
    fs.writeFileSync(this.anchorsFilePath, outputContent);
    console.log("📁 All anchors written to App/Anchors.js");
  }

  /**
   * Обрабатывает все найденные GLB файлы
   *
   * Основной метод, который:
   * 1. Находит все несжатые GLB файлы
   * 2. Обрабатывает каждый файл (кроме Images.glb)
   * 3. Записывает файл с якорями
   *
   * Примечание: Images.glb пропускается, так как обычно содержит
   * только текстуры без геометрии.
   */
  async processAllFiles() {
    const glbFiles = this.findUncompressedGLBFiles();

    if (glbFiles.length === 0) {
      console.log("No uncompressed .glb files found in /Data");
      return;
    }

    for (const filePath of glbFiles) {
      try {
        if (!filePath.includes("Images.glb")) {
          await this.processGLBFile(filePath);
        }
      } catch (error) {
        console.error(
          `❌ Failed: ${path.relative(this.dataDirectory, filePath)}\n`,
          error instanceof Error ? error.message : error,
        );
      }
    }

    this.writeAnchorsFile();
    console.log("✨ All files processed");
  }
}

/**
 * Запуск процесса компрессии
 *
 * Создает экземпляр компрессора и запускает обработку всех файлов.
 * В случае критической ошибки завершает процесс с кодом 1.
 */
const compressor = new GLBCompressor();
compressor.processAllFiles().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
