const fs = require("fs");
const path = require("path");
const { parse } = require("jsonc-parser");

/**
 * AssetKeeperGenerator
 * Generates TypeScript file with static getters for image and 3D model assets
 */
class AssetKeeperGenerator {
  constructor() {
    this.projectRoot = path.resolve(__dirname, "../..");
    this.settingsPath = path.join(this.projectRoot, "Settings", "default.json");

    this.outputDir = path.join(this.projectRoot, "App", "Generated");
    this.outputPath = path.join(this.outputDir, "AssetKeeper.ts");
  }

  /**
   * Main generation method
   */
  async generate() {
    try {
      console.log("🚀 Starting AssetKeeper generation...");

      // Ensure output directory exists
      this.ensureOutputDirectory();

      // Read and parse settings
      const settings = this.loadSettings();
      const assets = settings["Assets"] || {};

      console.log(`📊 Found ${Object.keys(assets).length} assets in settings`);

      // Generate TypeScript content
      const content = await this.generateContent(assets);

      // Write file
      fs.writeFileSync(this.outputPath, content, "utf-8");
      console.log(`✅ AssetKeeper.ts generated at: ${this.outputPath}`);

      // Show statistics
      this.showStatistics(assets);
    } catch (error) {
      console.error("❌ Error generating AssetKeeper:", error.message);
      process.exit(1);
    }
  }

  /**
   * Creates output directory if it doesn't exist
   */
  ensureOutputDirectory() {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
      console.log(`📁 Created directory: ${this.outputDir}`);
    }
  }

  /**
   * Loads and parses settings file
   */
  loadSettings() {
    if (!fs.existsSync(this.settingsPath)) {
      throw new Error(`Settings file not found: ${this.settingsPath}`);
    }

    const raw = fs.readFileSync(this.settingsPath, "utf-8");
    const settings = parse(raw);

    if (!settings) {
      throw new Error("Failed to parse settings file");
    }

    return settings;
  }

  /**
   * Generates TypeScript content
   */
  async generateContent(assets) {
    const lines = [];

    // Add header
    lines.push(...this.getFileHeader());

    // Process different asset types
    const imageAssets = this.processImageAssets(lines, assets);
    const glbAssets = this.processGlbAssets(lines, assets);

    // Close class
    lines.push("}");

    return lines.join("\n");
  }

  /**
   * Generates file header with imports and class declaration
   */
  getFileHeader() {
    return [
      "// Generated by Tools/AssetKeeperGenerator/AssetKeeperGenerator.js",
      "// Do not edit manually - this file is regenerated automatically",
      "",
      'import { Texture } from "three";',
      'import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";',
      "",
      "declare const App: {",
      "  ThreeAssets: {",
      "    [key: string]: unknown;",
      "  };",
      "};",
      "",
      "/**",
      " * AssetKeeper provides type-safe access to project assets",
      " */",
      "export class AssetKeeper {",
      "  /**",
      "   * Gets asset by key",
      "   * @param key Asset key to retrieve",
      "   * @returns The requested asset",
      "   * @throws Error if asset is not found",
      "   */",
      "  public static getUnknownAsset(key: string): unknown {",
      "    const asset = App.ThreeAssets[key];",
      "",
      "    if (!asset) {",
      "      throw new Error(`Asset not found: ${key}`);",
      "    }",
      "",
      "    return asset;",
      "  }",
      "",
      "  /**",
      "   * Gets texture asset by key",
      "   * @param key Asset key to retrieve",
      "   * @returns The requested texture",
      "   * @throws Error if asset is not found or not a texture",
      "   */",
      "  public static getTextureAsset(key: string): Texture {",
      "    const asset = this.getUnknownAsset(key);",
      "",
      "    if (!(asset instanceof Texture)) {",
      "      throw new Error(`Asset '${key}' is not a texture`);",
      "    }",
      "",
      "    return asset as Texture;",
      "  }",
      "",
      "  /**",
      "   * Gets GLTF asset by key",
      "   * @param key Asset key to retrieve",
      "   * @returns The requested GLTF",
      "   * @throws Error if asset is not found or not a GLTF",
      "   */",
      "  public static getGLTFAsset(key: string): GLTF {",
      "    const asset = this.getUnknownAsset(key);",
      "",
      '    if (!(typeof asset === "object" && asset !== null && "scene" in asset && "animations" in asset)) {',
      "      throw new Error(`Asset '${key}' is not a GLTF`);",
      "    }",
      "",
      "    return asset as GLTF;",
      "  }",
      "",
    ];
  }

  /**
   * Processes image assets and generates getters
   */
  processImageAssets(lines, assets) {
    const imageAssets = Object.entries(assets).filter(
      ([, value]) => value.type === "image",
    );

    if (imageAssets.length > 0) {
      lines.push("  // === IMAGE ASSETS ===");
      lines.push("");
    }

    for (const [key] of imageAssets) {
      lines.push(
        `  /**`,
        `   * Get image asset: ${key}`,
        `   * @returns Texture object`,
        `   */`,
        `  public static get ${this.sanitizePropertyName(key)}(): Texture {`,
        `    return this.getTextureAsset("${key}");`,
        `  }`,
        "",
      );
    }

    return imageAssets.length;
  }

  /**
   * Processes GLB/GLTF assets and generates getters
   */
  processGlbAssets(lines, assets) {
    const glbAssets = Object.entries(assets).filter(
      ([, value]) => value.type === "glb",
    );

    if (glbAssets.length > 0) {
      lines.push("  // === 3D MODEL ASSETS ===");
      lines.push("");
    }

    for (const [key] of glbAssets) {
      lines.push(
        `  /**`,
        `   * Get 3D model asset: ${key}`,
        `   * @returns GLTF object`,
        `   */`,
        `  public static get ${this.sanitizePropertyName(key)}(): GLTF {`,
        `    return this.getGLTFAsset("${key}");`,
        `  }`,
        "",
      );
    }

    return glbAssets.length;
  }

  /**
   * Sanitizes property names for TypeScript
   */
  sanitizePropertyName(name) {
    // Return as-is if already valid identifier
    if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) {
      return name;
    }

    // Use bracket notation for invalid identifiers
    return `["${name}"]`;
  }

  /**
   * Shows generation statistics
   */
  showStatistics(assets) {
    const stats = {
      image: 0,
      glb: 0,
      other: 0,
    };

    for (const asset of Object.values(assets)) {
      if (asset.type === "image") {
        stats.image++;
      } else if (asset.type === "glb") {
        stats.glb++;
      } else {
        stats.other++;
      }
    }

    console.log("\n📊 Asset Statistics:");
    console.log(`   🖼️  Images: ${stats.image}`);
    console.log(`   🎮 3D Models: ${stats.glb}`);
    if (stats.other > 0) {
      console.log(`   ❓ Other: ${stats.other}`);
    }
    console.log(`   📦 Generated Getters: ${stats.image + stats.glb}`);
  }
}

// Execute the generator
if (require.main === module) {
  (async () => {
    const generator = new AssetKeeperGenerator();
    await generator.generate();
  })().catch((error) => {
    console.error("💥 Fatal error:", error.message);
    process.exit(1);
  });
}

module.exports = AssetKeeperGenerator;
